apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: hf-cache
  namespace: ms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
