apiVersion: v1
kind: Namespace
metadata:
  name: ms
  labels:
    observability.homel.dev/telemetry-consumer: "true"
    observability.homel.dev/project: memory-steward
    observability.homel.dev/local-alloy: "true"
