import os
import json
import hashlib
import re
import logging
import uuid
from typing import Any, Dict, List, Optional
from collections import Counter

import psycopg
import requests
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from memory_steward.telemetry import StewardTelemetryWriter

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

def _req(name: str) -> str:
    v = os.environ.get(name)
    if not v:
        raise RuntimeError(f"Missing required env var: {name}")
    return v


def _opt(name: str, default: str = "") -> str:
    return os.environ.get(name, default)


def _svc_url(host_env: str, port_env: str, scheme: str = "http") -> str:
    host = _req(host_env)
    port = _req(port_env)
    return f"{scheme}://{host}:{port}"


POSTGRES_HOST = _req("POSTGRES_SERVICE_HOST")
POSTGRES_PORT = _req("POSTGRES_SERVICE_PORT")
POSTGRES_USER = _req("POSTGRES_USER")
POSTGRES_PASSWORD = _req("POSTGRES_PASSWORD")
POSTGRES_DB = _req("POSTGRES_DB")
POSTGRES_SSLMODE = _opt("POSTGRES_SSLMODE", "disable")
POSTGRES_APPNAME = _opt("POSTGRES_APPLICATION_NAME", "memory-steward")

POSTGRES_DSN = (
    f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}"
    f"@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
    f"?sslmode={POSTGRES_SSLMODE}&application_name={POSTGRES_APPNAME}"
)

QDRANT_URL = _svc_url("QDRANT_SERVICE_HOST", "QDRANT_SERVICE_PORT")
EMBEDDINGS_URL = _svc_url("EMBEDDINGS_SERVICE_HOST", "EMBEDDINGS_SERVICE_PORT")
QDRANT_COLLECTION = _req("QDRANT_COLLECTION")

STEWARD_LLM_BASE_URL = _svc_url("VLLM_STEWARD_SERVICE_HOST", "VLLM_STEWARD_SERVICE_PORT")
STEWARD_LLM_API_KEY = _opt("STEWARD_LLM_API_KEY", "local-token")
STEWARD_MODEL = _opt("STEWARD_MODEL", "").strip()

SPECULATIVE_RE = re.compile(
    r"\b(i think|probably|might|may|seems|guess|possibly|unclear)\b",
    re.IGNORECASE,
)

# ------------------------------------------------------------------------------
# Logging
# ------------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("uvicorn.error")

telemetry = StewardTelemetryWriter(POSTGRES_DSN)

app = FastAPI(title="homel-memory-steward", version="0.2")

# ------------------------------------------------------------------------------
# API Models
# ------------------------------------------------------------------------------

class AdmitTurnRequest(BaseModel):
    """
    Incoming admission request from Memory Router.

    request_id:
      - MUST be generated by Router
      - Used as primary key for telemetry.admission
    """
    request_id: str = Field(..., min_length=1)
    project_id: str = Field(..., min_length=1)

    scope: Optional[str] = None
    messages: List[Dict[str, str]]

    evidence_type: Optional[str] = None
    evidence_ref: Optional[str] = None
    max_fragments: int = 12


@app.get("/healthz")
def healthz():
    return {"ok": True}

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------

def _pg():
    return psycopg.connect(POSTGRES_DSN)


def _hash(s: str) -> str:
    return hashlib.sha256(s.encode()).hexdigest()


def _point_uuid(project_id: str, content: str) -> str:
    # Qdrant point id MUST be UUID or integer; keep deterministic/stable.
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"{project_id}\n{content}"))


def _embed(texts: List[str]) -> List[List[float]]:
    """
    Embed extracted fragments using embeddings service.
    """
    r = requests.post(
        f"{EMBEDDINGS_URL}/embed",
        json={"texts": texts, "normalize": True},
        timeout=60,
    )
    r.raise_for_status()
    return r.json()["vectors"]


def _extract(messages: List[Dict[str, str]], limit: int) -> List[str]:
    """
    Ask Steward LLM to extract atomic factual fragments.
    Canonical Envelope mapping compliant with Doc 04, Section 10.3.
    """

    # Collect user content deterministically
    user_inputs = [
        m["content"]
        for m in messages
        if m.get("role") == "user" and m.get("content")
    ]

    conversation_text = "\n".join(user_inputs).strip()

    
    envelope = {
        "policy_layer": {
            "admission_rules": [
                "Extract atomic, high-signal facts only.",
                "Store only stable user-asserted facts.",
                "Reject transient or emotional language.",
                "Detect contradictions with existing memory.",
                "Ignore conversational noise and pleasantries.",
                "If at least one stable fact exists, you MUST extract it."
            ]
        },
        "enforcement_protocol": {
            "steps": [
                "1. Read policy_layer.",
                "2. Interpret current_objective.",
                "3. Analyze current_objective.new_input.",
                "4. Extract factual statements matching admission_rules.",
                "5. Produce strict JSON decision."
            ]
        },
        "system_ontology": {
            "project_name": "Memory Steward",
            "role": "Control Plane Governance"
        },
        "retrieval_context": {},
        "dialogue_state": {},
        "current_objective": {
            "task": "memory_admission",
            "new_input": conversation_text,
            "max_fragments_allowed": limit,
            "decision_required": [
                "extract_facts",
                "detect_updates",
                "ignore_noise"
            ]
        },
        "final_reminder": (
            'Output MUST be strict JSON matching schema: {"fragments": ["..."]}.'
            'Do not output explanations.'
        )
    }

    canonical_envelope_str = json.dumps(envelope, indent=2)


    payload = {
        "model": STEWARD_MODEL,
        "messages": [
            {
                "role": "system",
                "content": canonical_envelope_str,
            }
        ],
        "temperature": 0.0,
        "response_format": {"type": "json_object"},
    }
    """
    payload = {
        "model": STEWARD_MODEL,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are the Control Plane Governance API. Execute the extraction task "
                    "defined in the following JSON configuration against the user's messages:\n\n"
                    f"{canonical_envelope_str}\n\n"
                    "EXAMPLE OUTPUT:\n"
                    "{\"fragments\": [\"User's primary programming language is Python.\"]}"
                ),
            }
        ] + messages,
        "temperature": 0.0,
        "response_format": {"type": "json_object"},
    }
    """
    r = requests.post(
        f"{STEWARD_LLM_BASE_URL}/v1/chat/completions",
        headers={"Authorization": f"Bearer {STEWARD_LLM_API_KEY}"},
        json=payload,
        timeout=120,
    )
    r.raise_for_status()

    frags = json.loads(r.json()["choices"][0]["message"]["content"]).get("fragments", [])[:limit]

    log.info("payload=%s, fragments=%s", payload, frags)

    #return json.loads(
    #    r.json()["choices"][0]["message"]["content"]
    #).get("fragments", [])[:limit]
    return frags

# ------------------------------------------------------------------------------
# Lexical Sparse Encoder (TF sparse vectors, minimal)
# ------------------------------------------------------------------------------

TOKEN_RE = re.compile(r"[a-zA-Z0-9]+")

# Global in-memory vocab (MVP)
# TODO: persist in Postgres or external store
_sparse_vocab: Dict[str, int] = {}


def _tokenize_lexical(text: str) -> List[str]:
    return TOKEN_RE.findall(text.lower())


def _sparse_vector(text: str) -> Dict[str, List[float]]:
    """
    Build sparse vector {indices, values} using term frequency.
    """
    tokens = _tokenize_lexical(text)
    counts = Counter(tokens)

    indices: List[int] = []
    values: List[float] = []

    for token, tf in counts.items():
        if token not in _sparse_vocab:
            _sparse_vocab[token] = len(_sparse_vocab)

        indices.append(_sparse_vocab[token])
        values.append(float(tf))

    return {"indices": indices, "values": values}

# ------------------------------------------------------------------------------
# Admission Endpoint (TELEMETRY WIRED)
# ------------------------------------------------------------------------------

@app.post("/admit")
def admit(req: AdmitTurnRequest):
    """
    Admit conversation turns into long-term memory.

    Telemetry guarantees:
      - Exactly one telemetry.admission row per request_id
      - Written even on failure
      - Never blocks Router
    """

    fragments_extracted = 0
    fragments_inserted = 0
    qdrant_upserts = 0
    ok = True
    error_detail: Optional[str] = None

    try:
        # ------------------------------------------------------------------
        # 1. Extract candidate memory fragments
        # ------------------------------------------------------------------
        frags = _extract(req.messages, req.max_fragments)
        fragments_extracted = len(frags)

        if not frags:
            return {"ok": True, "inserted": 0}

        log.info("fragments=%s", frags)
        # ------------------------------------------------------------------
        # 2. Embed fragments
        # ------------------------------------------------------------------
        vecs = _embed(frags)

        points: List[Dict[str, Any]] = []

        # ------------------------------------------------------------------
        # 3. Persist dynamic memory in Postgres (idempotent)
        # ------------------------------------------------------------------
        with _pg() as conn, conn.cursor() as cur:
            for i, content in enumerate(frags):
                speculative = bool(SPECULATIVE_RE.search(content))
                high_conf = (not speculative) and bool(req.evidence_type)

                content_hash = _hash(req.project_id + content)
                point_id = _point_uuid(req.project_id, content)

                cur.execute(
                    """
                    INSERT INTO dynamic_memory
                      (project_id, scope, type, content, content_hash,
                       high_confidence, evidence_type, evidence_ref, qdrant_point_id)
                    VALUES (%s,%s,'fact',%s,%s,%s,%s,%s,%s)
                    ON CONFLICT DO NOTHING
                    """,
                    (
                        req.project_id,
                        req.scope,
                        content,
                        content_hash,
                        high_conf,
                        req.evidence_type,
                        req.evidence_ref,
                        point_id,
                    ),
                )

                fragments_inserted += cur.rowcount

                sparse = _sparse_vector(content)

                points.append(
                    {
                        "id": point_id,
                        "vector": {
                            "dense": vecs[i],
                            "lexical": sparse,
                        },
                        "payload": {
                            "project_id": req.project_id,
                            "content": content,
                            "high_confidence": high_conf,
                        },
                    }
                )

        # ------------------------------------------------------------------
        # 4. Upsert into Qdrant (only if we have points)
        # ------------------------------------------------------------------
        if points:
            r = requests.put(
                f"{QDRANT_URL}/collections/{QDRANT_COLLECTION}/points?wait=true",
                json={"points": points},
                timeout=60,
            )
            if not r.ok:
                log.error("qdrant.upsert_failed status=%s body=%s", r.status_code, (r.text or "")[:2000])
            r.raise_for_status()

            qdrant_upserts = len(points)

        return {"ok": True, "inserted": fragments_inserted}

    except Exception as e:
        ok = False
        error_detail = str(e)
        log.exception("memory-steward admission failed")
        raise HTTPException(status_code=500, detail="admission failed")

    finally:
        # ------------------------------------------------------------------
        # 5. TELEMETRY WRITE (MANDATORY, BEST-EFFORT)
        # ------------------------------------------------------------------
        telemetry.admission_write(
            request_id=req.request_id,
            project_id=req.project_id,
            fragments_extracted=fragments_extracted,
            fragments_inserted=fragments_inserted,
            qdrant_upserts=qdrant_upserts,
            ok=ok,
            error_detail=error_detail,
        )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("memory_steward.server:app", host="0.0.0.0", port=8090, reload=False)
