apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: ms
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-read-configmaps
  namespace: ms
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-read-configmaps
  namespace: ms
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: ms
roleRef:
  kind: Role
  name: grafana-read-configmaps
  apiGroup: rbac.authorization.k8s.io

