apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: homel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-read-configmaps
  namespace: homel
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-read-configmaps
  namespace: homel
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: homel
roleRef:
  kind: Role
  name: grafana-read-configmaps
  apiGroup: rbac.authorization.k8s.io

